version: '3'
services:
  web:
    build: .
    ports:
      - "7755:7755"
    volumes:
      - .:/app
    command: bash -c "source env/bin/activate && flask db upgrade -d core/migrations/ && ./run.sh"
